/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.appperpustakaan;

import java.awt.Color;

/**
 *
 * @author nasan
 */
public class FEB extends javax.swing.JFrame {

    /**
     * Creates new form FEB
     */
    public FEB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        manajemenPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        akunPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bdPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ekoPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ekisPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pbPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pePanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        paPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pakPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FEB");

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.gray, java.awt.Color.darkGray));

        jLabel1.setFont(new java.awt.Font("Urdu Typesetting", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Fakultas Ekonomi dan Bisnis");

        manajemenPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manajemenPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manajemenPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manajemenPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manajemenPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                manajemenPanelMouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Manajemen");

        javax.swing.GroupLayout manajemenPanelLayout = new javax.swing.GroupLayout(manajemenPanel);
        manajemenPanel.setLayout(manajemenPanelLayout);
        manajemenPanelLayout.setHorizontalGroup(
            manajemenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manajemenPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        manajemenPanelLayout.setVerticalGroup(
            manajemenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manajemenPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        akunPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        akunPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                akunPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                akunPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                akunPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                akunPanelMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Akuntansi");

        javax.swing.GroupLayout akunPanelLayout = new javax.swing.GroupLayout(akunPanel);
        akunPanel.setLayout(akunPanelLayout);
        akunPanelLayout.setHorizontalGroup(
            akunPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(akunPanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        akunPanelLayout.setVerticalGroup(
            akunPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, akunPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        bdPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bdPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bdPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bdPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bdPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bdPanelMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Bisnis Digital");

        javax.swing.GroupLayout bdPanelLayout = new javax.swing.GroupLayout(bdPanel);
        bdPanel.setLayout(bdPanelLayout);
        bdPanelLayout.setHorizontalGroup(
            bdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bdPanelLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bdPanelLayout.setVerticalGroup(
            bdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bdPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        ekoPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ekoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ekoPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ekoPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ekoPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ekoPanelMouseReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Ekonomi");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout ekoPanelLayout = new javax.swing.GroupLayout(ekoPanel);
        ekoPanel.setLayout(ekoPanelLayout);
        ekoPanelLayout.setHorizontalGroup(
            ekoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ekoPanelLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ekoPanelLayout.setVerticalGroup(
            ekoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ekoPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        ekisPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ekisPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ekisPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ekisPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ekisPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ekisPanelMouseReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Ekonomi Islam");

        javax.swing.GroupLayout ekisPanelLayout = new javax.swing.GroupLayout(ekisPanel);
        ekisPanel.setLayout(ekisPanelLayout);
        ekisPanelLayout.setHorizontalGroup(
            ekisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ekisPanelLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ekisPanelLayout.setVerticalGroup(
            ekisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ekisPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        pbPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pbPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pbPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pbPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pbPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pbPanelMouseReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Pendidikan Bisnis");

        javax.swing.GroupLayout pbPanelLayout = new javax.swing.GroupLayout(pbPanel);
        pbPanel.setLayout(pbPanelLayout);
        pbPanelLayout.setHorizontalGroup(
            pbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbPanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pbPanelLayout.setVerticalGroup(
            pbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pbPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        pePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pePanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pePanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pePanelMouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Pendidikan Ekonomi");

        javax.swing.GroupLayout pePanelLayout = new javax.swing.GroupLayout(pePanel);
        pePanel.setLayout(pePanelLayout);
        pePanelLayout.setHorizontalGroup(
            pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(123, 123, 123))
        );
        pePanelLayout.setVerticalGroup(
            pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pePanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        paPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                paPanelMouseReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("Pendidikan Akuntansi");

        javax.swing.GroupLayout paPanelLayout = new javax.swing.GroupLayout(paPanel);
        paPanel.setLayout(paPanelLayout);
        paPanelLayout.setHorizontalGroup(
            paPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(115, 115, 115))
        );
        paPanelLayout.setVerticalGroup(
            paPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        pakPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pakPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pakPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pakPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pakPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pakPanelMouseReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("Pendidikan Administrasi Perkantoran");

        javax.swing.GroupLayout pakPanelLayout = new javax.swing.GroupLayout(pakPanel);
        pakPanel.setLayout(pakPanelLayout);
        pakPanelLayout.setHorizontalGroup(
            pakPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pakPanelLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(72, 72, 72))
        );
        pakPanelLayout.setVerticalGroup(
            pakPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pakPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ekoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ekisPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manajemenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(akunPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pbPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pakPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manajemenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(akunPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ekoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ekisPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pakPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void manajemenPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manajemenPanelMouseEntered
        // TODO add your handling code here:
        manajemenPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_manajemenPanelMouseEntered

    private void manajemenPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manajemenPanelMouseExited
        // TODO add your handling code here:
        manajemenPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_manajemenPanelMouseExited

    private void manajemenPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manajemenPanelMousePressed
        // TODO add your handling code here:
        manajemenPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_manajemenPanelMousePressed

    private void manajemenPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manajemenPanelMouseReleased
        // TODO add your handling code here:
        manajemenPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_manajemenPanelMouseReleased

    private void akunPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_akunPanelMouseEntered
        // TODO add your handling code here:
        akunPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_akunPanelMouseEntered

    private void akunPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_akunPanelMouseExited
        // TODO add your handling code here:
        akunPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_akunPanelMouseExited

    private void akunPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_akunPanelMousePressed
        // TODO add your handling code here:
        akunPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_akunPanelMousePressed

    private void akunPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_akunPanelMouseReleased
        // TODO add your handling code here:
        akunPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_akunPanelMouseReleased

    private void bdPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bdPanelMouseEntered
        // TODO add your handling code here:
        bdPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_bdPanelMouseEntered

    private void bdPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bdPanelMouseExited
        // TODO add your handling code here:
        bdPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_bdPanelMouseExited

    private void bdPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bdPanelMousePressed
        // TODO add your handling code here:
        bdPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_bdPanelMousePressed

    private void bdPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bdPanelMouseReleased
        // TODO add your handling code here:
        bdPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_bdPanelMouseReleased

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
 
    }//GEN-LAST:event_jLabel5MouseEntered

    private void ekoPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ekoPanelMouseEntered
        // TODO add your handling code here:
        ekoPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_ekoPanelMouseEntered

    private void ekoPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ekoPanelMouseExited
        // TODO add your handling code here:
        ekoPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_ekoPanelMouseExited

    private void ekoPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ekoPanelMousePressed
        // TODO add your handling code here:
        ekoPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_ekoPanelMousePressed

    private void ekoPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ekoPanelMouseReleased
        // TODO add your handling code here:
        ekoPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_ekoPanelMouseReleased

    private void ekisPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ekisPanelMouseEntered
        // TODO add your handling code here:
        ekisPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_ekisPanelMouseEntered

    private void ekisPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ekisPanelMouseExited
        // TODO add your handling code here:
        ekisPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_ekisPanelMouseExited

    private void ekisPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ekisPanelMousePressed
        // TODO add your handling code here:
        ekisPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_ekisPanelMousePressed

    private void ekisPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ekisPanelMouseReleased
        // TODO add your handling code here:
        ekisPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_ekisPanelMouseReleased

    private void pbPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbPanelMouseEntered
        // TODO add your handling code here:
        pbPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_pbPanelMouseEntered

    private void pbPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbPanelMouseExited
        // TODO add your handling code here:
        pbPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_pbPanelMouseExited

    private void pbPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbPanelMousePressed
        // TODO add your handling code here:
        pbPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_pbPanelMousePressed

    private void pbPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbPanelMouseReleased
        // TODO add your handling code here:
        pbPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_pbPanelMouseReleased

    private void pePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pePanelMouseEntered
        // TODO add your handling code here:
        pePanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_pePanelMouseEntered

    private void pePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pePanelMouseExited
        // TODO add your handling code here:
        pePanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_pePanelMouseExited

    private void pePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pePanelMousePressed
        // TODO add your handling code here:
        pePanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_pePanelMousePressed

    private void pePanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pePanelMouseReleased
        // TODO add your handling code here:
        pePanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_pePanelMouseReleased

    private void paPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paPanelMouseEntered
        // TODO add your handling code here:
        paPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_paPanelMouseEntered

    private void paPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paPanelMouseExited
        // TODO add your handling code here:
        paPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_paPanelMouseExited

    private void paPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paPanelMousePressed
        // TODO add your handling code here:
        paPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_paPanelMousePressed

    private void paPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paPanelMouseReleased
        // TODO add your handling code here:
        paPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_paPanelMouseReleased

    private void pakPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pakPanelMouseEntered
        // TODO add your handling code here:
        pakPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_pakPanelMouseEntered

    private void pakPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pakPanelMouseExited
        // TODO add your handling code here:
        pakPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_pakPanelMouseExited

    private void pakPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pakPanelMousePressed
        // TODO add your handling code here:
        pakPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_pakPanelMousePressed

    private void pakPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pakPanelMouseReleased
        // TODO add your handling code here:
        pakPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_pakPanelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FEB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FEB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FEB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FEB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FEB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel akunPanel;
    private javax.swing.JPanel bdPanel;
    private javax.swing.JPanel ekisPanel;
    private javax.swing.JPanel ekoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel manajemenPanel;
    private javax.swing.JPanel paPanel;
    private javax.swing.JPanel pakPanel;
    private javax.swing.JPanel pbPanel;
    private javax.swing.JPanel pePanel;
    // End of variables declaration//GEN-END:variables
}
