/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.appperpustakaan;

import java.awt.Color;

/**
 *
 * @author nasan
 */
public class FIKK extends javax.swing.JFrame {

    /**
     * Creates new form FIKK
     */
    public FIKK() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        giziPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ikPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        moPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pkoPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pjkrPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FIKK");

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.gray, java.awt.Color.darkGray));

        jLabel1.setFont(new java.awt.Font("Urdu Typesetting", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Fakultas Ilmu Keolahragaan dan Kesehatan");

        giziPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        giziPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                giziPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                giziPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                giziPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                giziPanelMouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Gizi");

        javax.swing.GroupLayout giziPanelLayout = new javax.swing.GroupLayout(giziPanel);
        giziPanel.setLayout(giziPanelLayout);
        giziPanelLayout.setHorizontalGroup(
            giziPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(giziPanelLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        giziPanelLayout.setVerticalGroup(
            giziPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, giziPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        ikPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ikPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ikPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ikPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ikPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ikPanelMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Ilmu Keolahragaan");

        javax.swing.GroupLayout ikPanelLayout = new javax.swing.GroupLayout(ikPanel);
        ikPanel.setLayout(ikPanelLayout);
        ikPanelLayout.setHorizontalGroup(
            ikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ikPanelLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel3)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        ikPanelLayout.setVerticalGroup(
            ikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ikPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        moPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        moPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                moPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                moPanelMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Manajemen Olahraga");

        javax.swing.GroupLayout moPanelLayout = new javax.swing.GroupLayout(moPanel);
        moPanel.setLayout(moPanelLayout);
        moPanelLayout.setHorizontalGroup(
            moPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moPanelLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        moPanelLayout.setVerticalGroup(
            moPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        pkoPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pkoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pkoPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pkoPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pkoPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pkoPanelMouseReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Pendidikan Kepelatihan Olahraga");

        javax.swing.GroupLayout pkoPanelLayout = new javax.swing.GroupLayout(pkoPanel);
        pkoPanel.setLayout(pkoPanelLayout);
        pkoPanelLayout.setHorizontalGroup(
            pkoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pkoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(107, 107, 107))
        );
        pkoPanelLayout.setVerticalGroup(
            pkoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pkoPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        pjkrPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pjkrPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pjkrPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pjkrPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pjkrPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pjkrPanelMouseReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Pendidikan Jasmani, Kesehatan, dan Rekreasi");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pjkrPanelLayout = new javax.swing.GroupLayout(pjkrPanel);
        pjkrPanel.setLayout(pjkrPanelLayout);
        pjkrPanelLayout.setHorizontalGroup(
            pjkrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pjkrPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel6)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        pjkrPanelLayout.setVerticalGroup(
            pjkrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pjkrPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(moPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pkoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pjkrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ikPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(giziPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(giziPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ikPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pkoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pjkrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void giziPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_giziPanelMouseEntered
        // TODO add your handling code here:
        giziPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_giziPanelMouseEntered

    private void giziPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_giziPanelMouseExited
        // TODO add your handling code here:
        giziPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_giziPanelMouseExited

    private void giziPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_giziPanelMousePressed
        // TODO add your handling code here:
        giziPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_giziPanelMousePressed

    private void giziPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_giziPanelMouseReleased
        // TODO add your handling code here:
        giziPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_giziPanelMouseReleased

    private void ikPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ikPanelMouseEntered
        // TODO add your handling code here:
        ikPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_ikPanelMouseEntered

    private void ikPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ikPanelMouseExited
        // TODO add your handling code here:
        ikPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_ikPanelMouseExited

    private void ikPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ikPanelMousePressed
        // TODO add your handling code here:
        ikPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_ikPanelMousePressed

    private void ikPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ikPanelMouseReleased
        // TODO add your handling code here:
        ikPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_ikPanelMouseReleased

    private void moPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moPanelMouseEntered
        // TODO add your handling code here:
        moPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_moPanelMouseEntered

    private void moPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moPanelMouseExited
        // TODO add your handling code here:
        moPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_moPanelMouseExited

    private void moPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moPanelMousePressed
        // TODO add your handling code here:
        moPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_moPanelMousePressed

    private void moPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moPanelMouseReleased
        // TODO add your handling code here:
        moPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_moPanelMouseReleased

    private void pkoPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pkoPanelMouseEntered
        // TODO add your handling code here:
        pkoPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_pkoPanelMouseEntered

    private void pkoPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pkoPanelMouseExited
        // TODO add your handling code here:
        pkoPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_pkoPanelMouseExited

    private void pkoPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pkoPanelMousePressed
        // TODO add your handling code here:
        pkoPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_pkoPanelMousePressed

    private void pkoPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pkoPanelMouseReleased
        // TODO add your handling code here:
        pkoPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_pkoPanelMouseReleased

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered

    }//GEN-LAST:event_jLabel6MouseEntered

    private void pjkrPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pjkrPanelMouseEntered
        // TODO add your handling code here:
        pjkrPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_pjkrPanelMouseEntered

    private void pjkrPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pjkrPanelMouseExited
        // TODO add your handling code here:
        pjkrPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_pjkrPanelMouseExited

    private void pjkrPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pjkrPanelMousePressed
        // TODO add your handling code here:
       pjkrPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_pjkrPanelMousePressed

    private void pjkrPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pjkrPanelMouseReleased
        // TODO add your handling code here:
        pjkrPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_pjkrPanelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FIKK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FIKK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FIKK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FIKK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FIKK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel giziPanel;
    private javax.swing.JPanel ikPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel moPanel;
    private javax.swing.JPanel pjkrPanel;
    private javax.swing.JPanel pkoPanel;
    // End of variables declaration//GEN-END:variables
}
