/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.appperpustakaan;

import java.awt.Color;

/**
 *
 * @author nasan
 */
public class FISH extends javax.swing.JFrame {

    /**
     * Creates new form FISH
     */
    public FISH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        geoPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sejPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ihPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ianPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        sosPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ilkomPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ilpolPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ipsPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pknPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FISH");

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.gray, java.awt.Color.darkGray));

        jLabel1.setFont(new java.awt.Font("Urdu Typesetting", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Fakultas Ilmu Sosial dan Hukum");

        geoPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        geoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                geoPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                geoPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                geoPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                geoPanelMouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Pendidikan Geografi");

        javax.swing.GroupLayout geoPanelLayout = new javax.swing.GroupLayout(geoPanel);
        geoPanel.setLayout(geoPanelLayout);
        geoPanelLayout.setHorizontalGroup(
            geoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, geoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(163, 163, 163))
        );
        geoPanelLayout.setVerticalGroup(
            geoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, geoPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        sejPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sejPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sejPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sejPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sejPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sejPanelMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Pendidikan Sejarah");

        javax.swing.GroupLayout sejPanelLayout = new javax.swing.GroupLayout(sejPanel);
        sejPanel.setLayout(sejPanelLayout);
        sejPanelLayout.setHorizontalGroup(
            sejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sejPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(165, 165, 165))
        );
        sejPanelLayout.setVerticalGroup(
            sejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sejPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        ihPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ihPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ihPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ihPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ihPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ihPanelMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Ilmu Hukum");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout ihPanelLayout = new javax.swing.GroupLayout(ihPanel);
        ihPanel.setLayout(ihPanelLayout);
        ihPanelLayout.setHorizontalGroup(
            ihPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ihPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(183, 183, 183))
        );
        ihPanelLayout.setVerticalGroup(
            ihPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ihPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        ianPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ianPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ianPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ianPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ianPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ianPanelMouseReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Ilmu Administrasi Negara");

        javax.swing.GroupLayout ianPanelLayout = new javax.swing.GroupLayout(ianPanel);
        ianPanel.setLayout(ianPanelLayout);
        ianPanelLayout.setHorizontalGroup(
            ianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ianPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(143, 143, 143))
        );
        ianPanelLayout.setVerticalGroup(
            ianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ianPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        sosPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sosPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sosPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sosPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sosPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sosPanelMouseReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Sosiologi");

        javax.swing.GroupLayout sosPanelLayout = new javax.swing.GroupLayout(sosPanel);
        sosPanel.setLayout(sosPanelLayout);
        sosPanelLayout.setHorizontalGroup(
            sosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sosPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(202, 202, 202))
        );
        sosPanelLayout.setVerticalGroup(
            sosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sosPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        ilkomPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ilkomPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ilkomPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ilkomPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ilkomPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ilkomPanelMouseReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Ilmu Komunikasi");

        javax.swing.GroupLayout ilkomPanelLayout = new javax.swing.GroupLayout(ilkomPanel);
        ilkomPanel.setLayout(ilkomPanelLayout);
        ilkomPanelLayout.setHorizontalGroup(
            ilkomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ilkomPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(172, 172, 172))
        );
        ilkomPanelLayout.setVerticalGroup(
            ilkomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ilkomPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        ilpolPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ilpolPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ilpolPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ilpolPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ilpolPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ilpolPanelMouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Ilmu Politik");

        javax.swing.GroupLayout ilpolPanelLayout = new javax.swing.GroupLayout(ilpolPanel);
        ilpolPanel.setLayout(ilpolPanelLayout);
        ilpolPanelLayout.setHorizontalGroup(
            ilpolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ilpolPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(189, 189, 189))
        );
        ilpolPanelLayout.setVerticalGroup(
            ilpolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ilpolPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        ipsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ipsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ipsPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ipsPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ipsPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ipsPanelMouseReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("Pendidikan IPS");

        javax.swing.GroupLayout ipsPanelLayout = new javax.swing.GroupLayout(ipsPanel);
        ipsPanel.setLayout(ipsPanelLayout);
        ipsPanelLayout.setHorizontalGroup(
            ipsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ipsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(182, 182, 182))
        );
        ipsPanelLayout.setVerticalGroup(
            ipsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ipsPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        pknPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pknPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pknPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pknPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pknPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pknPanelMouseReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("Pendidikan Pancasila dan Kewarganegaraan");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pknPanelLayout = new javax.swing.GroupLayout(pknPanel);
        pknPanel.setLayout(pknPanelLayout);
        pknPanelLayout.setHorizontalGroup(
            pknPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pknPanelLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(79, 79, 79))
        );
        pknPanelLayout.setVerticalGroup(
            pknPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pknPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pknPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ihPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ianPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sejPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ipsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ilpolPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ilkomPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(geoPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(76, 76, 76))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(geoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ihPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ianPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ilkomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ilpolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ipsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pknPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void geoPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geoPanelMouseEntered
        // TODO add your handling code here:
        geoPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_geoPanelMouseEntered

    private void geoPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geoPanelMouseExited
        // TODO add your handling code here:
        geoPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_geoPanelMouseExited

    private void geoPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geoPanelMousePressed
        // TODO add your handling code here:
        geoPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_geoPanelMousePressed

    private void geoPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geoPanelMouseReleased
        // TODO add your handling code here:
        geoPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_geoPanelMouseReleased

    private void sejPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sejPanelMouseEntered
        // TODO add your handling code here:
        sejPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_sejPanelMouseEntered

    private void sejPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sejPanelMouseExited
        // TODO add your handling code here:
        sejPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_sejPanelMouseExited

    private void sejPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sejPanelMousePressed
        // TODO add your handling code here:
        sejPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_sejPanelMousePressed

    private void sejPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sejPanelMouseReleased
        // TODO add your handling code here:
        sejPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_sejPanelMouseReleased

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
      
    }//GEN-LAST:event_jLabel4MouseEntered

    private void ihPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ihPanelMouseEntered
        // TODO add your handling code here:
        ihPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_ihPanelMouseEntered

    private void ihPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ihPanelMouseExited
        // TODO add your handling code here:
        ihPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_ihPanelMouseExited

    private void ihPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ihPanelMousePressed
        // TODO add your handling code here:
        ihPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_ihPanelMousePressed

    private void ihPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ihPanelMouseReleased
        // TODO add your handling code here:
        ihPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_ihPanelMouseReleased

    private void ianPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ianPanelMouseEntered
        // TODO add your handling code here:
        ianPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_ianPanelMouseEntered

    private void ianPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ianPanelMouseExited
        // TODO add your handling code here:
        ianPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_ianPanelMouseExited

    private void ianPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ianPanelMousePressed
        // TODO add your handling code here:
        ianPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_ianPanelMousePressed

    private void ianPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ianPanelMouseReleased
        // TODO add your handling code here:
        ianPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_ianPanelMouseReleased

    private void sosPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sosPanelMouseEntered
        // TODO add your handling code here:
        sosPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_sosPanelMouseEntered

    private void sosPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sosPanelMouseExited
        // TODO add your handling code here:
        sosPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_sosPanelMouseExited

    private void sosPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sosPanelMousePressed
        // TODO add your handling code here:
        sosPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_sosPanelMousePressed

    private void sosPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sosPanelMouseReleased
        // TODO add your handling code here:
        sosPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_sosPanelMouseReleased

    private void ilkomPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ilkomPanelMouseEntered
        // TODO add your handling code here:
        ilkomPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_ilkomPanelMouseEntered

    private void ilkomPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ilkomPanelMouseExited
        // TODO add your handling code here:
        ilkomPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_ilkomPanelMouseExited

    private void ilkomPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ilkomPanelMousePressed
        // TODO add your handling code here:
        ilkomPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_ilkomPanelMousePressed

    private void ilkomPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ilkomPanelMouseReleased
        // TODO add your handling code here:
        ilkomPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_ilkomPanelMouseReleased

    private void ilpolPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ilpolPanelMouseEntered
        // TODO add your handling code here:
        ilpolPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_ilpolPanelMouseEntered

    private void ilpolPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ilpolPanelMouseExited
        // TODO add your handling code here:
        ilpolPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_ilpolPanelMouseExited

    private void ilpolPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ilpolPanelMousePressed
        // TODO add your handling code here:
        ilpolPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_ilpolPanelMousePressed

    private void ilpolPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ilpolPanelMouseReleased
        // TODO add your handling code here:
        ilpolPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_ilpolPanelMouseReleased

    private void ipsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ipsPanelMouseEntered
        // TODO add your handling code here:
        ipsPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_ipsPanelMouseEntered

    private void ipsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ipsPanelMouseExited
        // TODO add your handling code here:
        ipsPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_ipsPanelMouseExited

    private void ipsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ipsPanelMousePressed
        // TODO add your handling code here:
        ipsPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_ipsPanelMousePressed

    private void ipsPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ipsPanelMouseReleased
        // TODO add your handling code here:
        ipsPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_ipsPanelMouseReleased

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
     
    }//GEN-LAST:event_jLabel10MouseEntered

    private void pknPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pknPanelMouseEntered
        // TODO add your handling code here:
        pknPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_pknPanelMouseEntered

    private void pknPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pknPanelMouseExited
        // TODO add your handling code here:
        pknPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_pknPanelMouseExited

    private void pknPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pknPanelMousePressed
        // TODO add your handling code here:
        pknPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_pknPanelMousePressed

    private void pknPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pknPanelMouseReleased
        // TODO add your handling code here:
        pknPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_pknPanelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FISH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FISH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FISH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FISH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FISH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel geoPanel;
    private javax.swing.JPanel ianPanel;
    private javax.swing.JPanel ihPanel;
    private javax.swing.JPanel ilkomPanel;
    private javax.swing.JPanel ilpolPanel;
    private javax.swing.JPanel ipsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pknPanel;
    private javax.swing.JPanel sejPanel;
    private javax.swing.JPanel sosPanel;
    // End of variables declaration//GEN-END:variables
}
