/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.appperpustakaan;

import java.awt.Color;

/**
 *
 * @author nasan
 */
public class FMIPA extends javax.swing.JFrame {

    /**
     * Creates new form FMIPA
     */
    public FMIPA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mtkPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bioPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fisikaPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        kimiaPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pmPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pbPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pfPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pkPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        sdPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        psPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FMIPA");

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.gray, java.awt.Color.darkGray));

        jLabel1.setFont(new java.awt.Font("Urdu Typesetting", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Fakultas Matematika dan Ilmu Pengetahuan Alam");

        mtkPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mtkPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mtkPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mtkPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mtkPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mtkPanelMouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Matematika");

        javax.swing.GroupLayout mtkPanelLayout = new javax.swing.GroupLayout(mtkPanel);
        mtkPanel.setLayout(mtkPanelLayout);
        mtkPanelLayout.setHorizontalGroup(
            mtkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mtkPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(201, 201, 201))
        );
        mtkPanelLayout.setVerticalGroup(
            mtkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mtkPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        bioPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bioPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bioPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bioPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bioPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bioPanelMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Biologi");

        javax.swing.GroupLayout bioPanelLayout = new javax.swing.GroupLayout(bioPanel);
        bioPanel.setLayout(bioPanelLayout);
        bioPanelLayout.setHorizontalGroup(
            bioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bioPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(216, 216, 216))
        );
        bioPanelLayout.setVerticalGroup(
            bioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bioPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        fisikaPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fisikaPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fisikaPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fisikaPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fisikaPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fisikaPanelMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Fisika");

        javax.swing.GroupLayout fisikaPanelLayout = new javax.swing.GroupLayout(fisikaPanel);
        fisikaPanel.setLayout(fisikaPanelLayout);
        fisikaPanelLayout.setHorizontalGroup(
            fisikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fisikaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(214, 214, 214))
        );
        fisikaPanelLayout.setVerticalGroup(
            fisikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fisikaPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        kimiaPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kimiaPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kimiaPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kimiaPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kimiaPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                kimiaPanelMouseReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Kimia");

        javax.swing.GroupLayout kimiaPanelLayout = new javax.swing.GroupLayout(kimiaPanel);
        kimiaPanel.setLayout(kimiaPanelLayout);
        kimiaPanelLayout.setHorizontalGroup(
            kimiaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kimiaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(215, 215, 215))
        );
        kimiaPanelLayout.setVerticalGroup(
            kimiaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kimiaPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        pmPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pmPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pmPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pmPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pmPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pmPanelMouseReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Pendidikan Matematika");

        javax.swing.GroupLayout pmPanelLayout = new javax.swing.GroupLayout(pmPanel);
        pmPanel.setLayout(pmPanelLayout);
        pmPanelLayout.setHorizontalGroup(
            pmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pmPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(163, 163, 163))
        );
        pmPanelLayout.setVerticalGroup(
            pmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pmPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        pbPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pbPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pbPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pbPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pbPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pbPanelMouseReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Pendidikan Biologi");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pbPanelLayout = new javax.swing.GroupLayout(pbPanel);
        pbPanel.setLayout(pbPanelLayout);
        pbPanelLayout.setHorizontalGroup(
            pbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pbPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(180, 180, 180))
        );
        pbPanelLayout.setVerticalGroup(
            pbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pbPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        pfPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pfPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pfPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pfPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pfPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pfPanelMouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Pendidikan Fisika");

        javax.swing.GroupLayout pfPanelLayout = new javax.swing.GroupLayout(pfPanel);
        pfPanel.setLayout(pfPanelLayout);
        pfPanelLayout.setHorizontalGroup(
            pfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pfPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(184, 184, 184))
        );
        pfPanelLayout.setVerticalGroup(
            pfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pfPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        pkPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pkPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pkPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pkPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pkPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pkPanelMouseReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("Pendidikan Kimia");

        javax.swing.GroupLayout pkPanelLayout = new javax.swing.GroupLayout(pkPanel);
        pkPanel.setLayout(pkPanelLayout);
        pkPanelLayout.setHorizontalGroup(
            pkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pkPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(184, 184, 184))
        );
        pkPanelLayout.setVerticalGroup(
            pkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pkPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        sdPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sdPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sdPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sdPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sdPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sdPanelMouseReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("Sains Data");

        javax.swing.GroupLayout sdPanelLayout = new javax.swing.GroupLayout(sdPanel);
        sdPanel.setLayout(sdPanelLayout);
        sdPanelLayout.setHorizontalGroup(
            sdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sdPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(204, 204, 204))
        );
        sdPanelLayout.setVerticalGroup(
            sdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sdPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        psPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        psPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                psPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                psPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                psPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                psPanelMouseReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("Pendidikan Sains");

        javax.swing.GroupLayout psPanelLayout = new javax.swing.GroupLayout(psPanel);
        psPanel.setLayout(psPanelLayout);
        psPanelLayout.setHorizontalGroup(
            psPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, psPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(181, 181, 181))
        );
        psPanelLayout.setVerticalGroup(
            psPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, psPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fisikaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mtkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kimiaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pmPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pbPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pfPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pkPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sdPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(psPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mtkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fisikaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kimiaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(psPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mtkPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mtkPanelMouseEntered
        // TODO add your handling code here:
        mtkPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_mtkPanelMouseEntered

    private void mtkPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mtkPanelMouseExited
        // TODO add your handling code here:
        mtkPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_mtkPanelMouseExited

    private void mtkPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mtkPanelMousePressed
        // TODO add your handling code here:
        mtkPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_mtkPanelMousePressed

    private void mtkPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mtkPanelMouseReleased
        // TODO add your handling code here:
        mtkPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_mtkPanelMouseReleased

    private void bioPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bioPanelMouseEntered
        // TODO add your handling code here:
        bioPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_bioPanelMouseEntered

    private void bioPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bioPanelMouseExited
        // TODO add your handling code here:
        bioPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_bioPanelMouseExited

    private void bioPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bioPanelMousePressed
        // TODO add your handling code here:
        bioPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_bioPanelMousePressed

    private void bioPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bioPanelMouseReleased
        // TODO add your handling code here:
        bioPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_bioPanelMouseReleased

    private void fisikaPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fisikaPanelMouseEntered
        // TODO add your handling code here:
        fisikaPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_fisikaPanelMouseEntered

    private void fisikaPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fisikaPanelMouseExited
        // TODO add your handling code here:
        fisikaPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_fisikaPanelMouseExited

    private void fisikaPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fisikaPanelMousePressed
        // TODO add your handling code here:
        fisikaPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_fisikaPanelMousePressed

    private void fisikaPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fisikaPanelMouseReleased
        // TODO add your handling code here:
        fisikaPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_fisikaPanelMouseReleased

    private void kimiaPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kimiaPanelMouseEntered
        // TODO add your handling code here:
        kimiaPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_kimiaPanelMouseEntered

    private void kimiaPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kimiaPanelMouseExited
        // TODO add your handling code here:
        kimiaPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_kimiaPanelMouseExited

    private void kimiaPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kimiaPanelMousePressed
        // TODO add your handling code here:
        kimiaPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_kimiaPanelMousePressed

    private void kimiaPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kimiaPanelMouseReleased
        // TODO add your handling code here:
        kimiaPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_kimiaPanelMouseReleased

    private void pmPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmPanelMouseEntered
        // TODO add your handling code here:
        pmPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_pmPanelMouseEntered

    private void pmPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmPanelMouseExited
        // TODO add your handling code here:
        pmPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_pmPanelMouseExited

    private void pmPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmPanelMousePressed
        // TODO add your handling code here:
        pmPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_pmPanelMousePressed

    private void pmPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmPanelMouseReleased
        // TODO add your handling code here:
        pmPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_pmPanelMouseReleased

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered

    }//GEN-LAST:event_jLabel7MouseEntered

    private void pbPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbPanelMouseEntered
        // TODO add your handling code here:
        pbPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_pbPanelMouseEntered

    private void pbPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbPanelMouseExited
        // TODO add your handling code here:
        pbPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_pbPanelMouseExited

    private void pbPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbPanelMousePressed
        // TODO add your handling code here:
        pbPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_pbPanelMousePressed

    private void pbPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbPanelMouseReleased
        // TODO add your handling code here:
        pbPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_pbPanelMouseReleased

    private void pfPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfPanelMouseEntered
        // TODO add your handling code here:
        pfPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_pfPanelMouseEntered

    private void pfPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfPanelMouseExited
        // TODO add your handling code here:
        pfPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_pfPanelMouseExited

    private void pfPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfPanelMousePressed
        // TODO add your handling code here:
        pfPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_pfPanelMousePressed

    private void pfPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfPanelMouseReleased
        // TODO add your handling code here:
        pfPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_pfPanelMouseReleased

    private void pkPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pkPanelMouseEntered
        // TODO add your handling code here:
        pkPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_pkPanelMouseEntered

    private void pkPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pkPanelMouseExited
        // TODO add your handling code here:
        pkPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_pkPanelMouseExited

    private void pkPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pkPanelMousePressed
        // TODO add your handling code here:
        pkPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_pkPanelMousePressed

    private void pkPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pkPanelMouseReleased
        // TODO add your handling code here:
        pkPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_pkPanelMouseReleased

    private void sdPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sdPanelMouseEntered
        // TODO add your handling code here:
        sdPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_sdPanelMouseEntered

    private void sdPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sdPanelMouseExited
        // TODO add your handling code here:
        sdPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_sdPanelMouseExited

    private void sdPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sdPanelMousePressed
        // TODO add your handling code here:
        sdPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_sdPanelMousePressed

    private void sdPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sdPanelMouseReleased
        // TODO add your handling code here:
        sdPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_sdPanelMouseReleased

    private void psPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psPanelMouseEntered
        // TODO add your handling code here:
        psPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_psPanelMouseEntered

    private void psPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psPanelMouseExited
        // TODO add your handling code here:
        psPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_psPanelMouseExited

    private void psPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psPanelMousePressed
        // TODO add your handling code here:
        psPanel.setBackground(new Color(155,89,182));
    }//GEN-LAST:event_psPanelMousePressed

    private void psPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psPanelMouseReleased
        // TODO add your handling code here:
       psPanel.setBackground(new Color(189, 195, 199));
    }//GEN-LAST:event_psPanelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMIPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMIPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMIPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMIPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMIPA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bioPanel;
    private javax.swing.JPanel fisikaPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel kimiaPanel;
    private javax.swing.JPanel mtkPanel;
    private javax.swing.JPanel pbPanel;
    private javax.swing.JPanel pfPanel;
    private javax.swing.JPanel pkPanel;
    private javax.swing.JPanel pmPanel;
    private javax.swing.JPanel psPanel;
    private javax.swing.JPanel sdPanel;
    // End of variables declaration//GEN-END:variables
}
