/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.appperpustakaan;

import java.awt.Color;

/**
 *
 * @author nasan
 */
public class FT extends javax.swing.JFrame {

    /**
     * Creates new form FT
     */
    public FT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tiPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        siPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ptiPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tmPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ptmPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ptePanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tsPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        ptbPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tabogPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        tabusPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        trPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FT");

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.gray, java.awt.Color.darkGray));

        jLabel1.setFont(new java.awt.Font("Urdu Typesetting", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Fakultas Teknik");

        tiPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tiPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tiPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tiPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tiPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tiPanelMouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Teknik Informatika");

        javax.swing.GroupLayout tiPanelLayout = new javax.swing.GroupLayout(tiPanel);
        tiPanel.setLayout(tiPanelLayout);
        tiPanelLayout.setHorizontalGroup(
            tiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tiPanelLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(156, 156, 156))
        );
        tiPanelLayout.setVerticalGroup(
            tiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tiPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        siPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                siPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                siPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                siPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                siPanelMouseReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Sistem Informasi");

        javax.swing.GroupLayout siPanelLayout = new javax.swing.GroupLayout(siPanel);
        siPanel.setLayout(siPanelLayout);
        siPanelLayout.setHorizontalGroup(
            siPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siPanelLayout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(168, 168, 168))
        );
        siPanelLayout.setVerticalGroup(
            siPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        ptiPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ptiPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ptiPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ptiPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ptiPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ptiPanelMouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Pendidikan Teknologi Informasi");

        javax.swing.GroupLayout ptiPanelLayout = new javax.swing.GroupLayout(ptiPanel);
        ptiPanel.setLayout(ptiPanelLayout);
        ptiPanelLayout.setHorizontalGroup(
            ptiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ptiPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(126, 126, 126))
        );
        ptiPanelLayout.setVerticalGroup(
            ptiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ptiPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        tmPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tmPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tmPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tmPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tmPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tmPanelMouseReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("Teknik Mesin");

        javax.swing.GroupLayout tmPanelLayout = new javax.swing.GroupLayout(tmPanel);
        tmPanel.setLayout(tmPanelLayout);
        tmPanelLayout.setHorizontalGroup(
            tmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tmPanelLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tmPanelLayout.setVerticalGroup(
            tmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tmPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        ptmPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ptmPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ptmPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ptmPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ptmPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ptmPanelMouseReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("Pendidikan Teknik Mesin");

        javax.swing.GroupLayout ptmPanelLayout = new javax.swing.GroupLayout(ptmPanel);
        ptmPanel.setLayout(ptmPanelLayout);
        ptmPanelLayout.setHorizontalGroup(
            ptmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptmPanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ptmPanelLayout.setVerticalGroup(
            ptmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ptmPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        tePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tePanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tePanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tePanelMouseReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("Teknik Elektro");

        javax.swing.GroupLayout tePanelLayout = new javax.swing.GroupLayout(tePanel);
        tePanel.setLayout(tePanelLayout);
        tePanelLayout.setHorizontalGroup(
            tePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tePanelLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel11)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        tePanelLayout.setVerticalGroup(
            tePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tePanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        ptePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ptePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ptePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ptePanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ptePanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ptePanelMouseReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 51));
        jLabel12.setText("Pendidikan Teknik Elektro");

        javax.swing.GroupLayout ptePanelLayout = new javax.swing.GroupLayout(ptePanel);
        ptePanel.setLayout(ptePanelLayout);
        ptePanelLayout.setHorizontalGroup(
            ptePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptePanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ptePanelLayout.setVerticalGroup(
            ptePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ptePanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        tsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tsPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tsPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tsPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tsPanelMouseReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 51));
        jLabel13.setText("Teknik Sipil");

        javax.swing.GroupLayout tsPanelLayout = new javax.swing.GroupLayout(tsPanel);
        tsPanel.setLayout(tsPanelLayout);
        tsPanelLayout.setHorizontalGroup(
            tsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tsPanelLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tsPanelLayout.setVerticalGroup(
            tsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tsPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        ptbPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ptbPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ptbPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ptbPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ptbPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ptbPanelMouseReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 51));
        jLabel14.setText("Pendidikan Teknik Bangunan");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout ptbPanelLayout = new javax.swing.GroupLayout(ptbPanel);
        ptbPanel.setLayout(ptbPanelLayout);
        ptbPanelLayout.setHorizontalGroup(
            ptbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptbPanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ptbPanelLayout.setVerticalGroup(
            ptbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ptbPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        tabogPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabogPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabogPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tabogPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabogPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabogPanelMouseReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 51));
        jLabel15.setText("Pendidikan Tata Boga");

        javax.swing.GroupLayout tabogPanelLayout = new javax.swing.GroupLayout(tabogPanel);
        tabogPanel.setLayout(tabogPanelLayout);
        tabogPanelLayout.setHorizontalGroup(
            tabogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabogPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(153, 153, 153))
        );
        tabogPanelLayout.setVerticalGroup(
            tabogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabogPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        tabusPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabusPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabusPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tabusPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabusPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabusPanelMouseReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 51));
        jLabel16.setText("Pendidikan Tata Busana");

        javax.swing.GroupLayout tabusPanelLayout = new javax.swing.GroupLayout(tabusPanel);
        tabusPanel.setLayout(tabusPanelLayout);
        tabusPanelLayout.setHorizontalGroup(
            tabusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabusPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(142, 142, 142))
        );
        tabusPanelLayout.setVerticalGroup(
            tabusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabusPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        trPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                trPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                trPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                trPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                trPanelMouseReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 51));
        jLabel17.setText("Pendidikan Tata Rias");

        javax.swing.GroupLayout trPanelLayout = new javax.swing.GroupLayout(trPanel);
        trPanel.setLayout(trPanelLayout);
        trPanelLayout.setHorizontalGroup(
            trPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(152, 152, 152))
        );
        trPanelLayout.setVerticalGroup(
            trPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(siPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ptmPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tmPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ptiPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(ptePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ptbPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tabogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tabusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(trPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(140, 140, 140))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(siPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ptiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ptmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ptePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ptbPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabogPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tiPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tiPanelMouseEntered
        // TODO add your handling code here:
        tiPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_tiPanelMouseEntered

    private void tiPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tiPanelMouseExited
        // TODO add your handling code here:
        tiPanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_tiPanelMouseExited

    private void tiPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tiPanelMousePressed
        // TODO add your handling code here:
        tiPanel.setBackground(new Color (155, 89, 182));
    }//GEN-LAST:event_tiPanelMousePressed

    private void tiPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tiPanelMouseReleased
        // TODO add your handling code here:
        tiPanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_tiPanelMouseReleased

    private void siPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siPanelMouseEntered
        // TODO add your handling code here:
        siPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_siPanelMouseEntered

    private void siPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siPanelMouseExited
        // TODO add your handling code here:
        siPanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_siPanelMouseExited

    private void siPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siPanelMousePressed
        // TODO add your handling code here:
        siPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_siPanelMousePressed

    private void siPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siPanelMouseReleased
        // TODO add your handling code here:
        siPanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_siPanelMouseReleased

    private void ptiPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptiPanelMouseEntered
        // TODO add your handling code here:
        ptiPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_ptiPanelMouseEntered

    private void ptiPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptiPanelMouseExited
        // TODO add your handling code here:
        ptiPanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_ptiPanelMouseExited

    private void ptiPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptiPanelMousePressed
        // TODO add your handling code here:
        ptiPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_ptiPanelMousePressed

    private void ptiPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptiPanelMouseReleased
        // TODO add your handling code here:
        ptiPanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_ptiPanelMouseReleased

    private void tmPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmPanelMouseEntered
        // TODO add your handling code here:
        tmPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_tmPanelMouseEntered

    private void tmPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmPanelMouseExited
        // TODO add your handling code here:
        tmPanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_tmPanelMouseExited

    private void tmPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmPanelMousePressed
        // TODO add your handling code here:
        tmPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_tmPanelMousePressed

    private void tmPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmPanelMouseReleased
        // TODO add your handling code here:
        tmPanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_tmPanelMouseReleased

    private void ptmPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptmPanelMouseEntered
        // TODO add your handling code here:
        ptmPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_ptmPanelMouseEntered

    private void ptmPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptmPanelMouseExited
        // TODO add your handling code here:
        ptmPanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_ptmPanelMouseExited

    private void ptmPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptmPanelMousePressed
        // TODO add your handling code here:
        ptmPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_ptmPanelMousePressed

    private void ptmPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptmPanelMouseReleased
        // TODO add your handling code here:
        ptmPanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_ptmPanelMouseReleased

    private void tePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tePanelMouseEntered
        // TODO add your handling code here:
        tePanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_tePanelMouseEntered

    private void tePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tePanelMouseExited
        // TODO add your handling code here:
        tePanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_tePanelMouseExited

    private void tePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tePanelMousePressed
        // TODO add your handling code here:
        tePanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_tePanelMousePressed

    private void tePanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tePanelMouseReleased
        // TODO add your handling code here:
        tePanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_tePanelMouseReleased

    private void ptePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptePanelMouseEntered
        // TODO add your handling code here:
        ptePanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_ptePanelMouseEntered

    private void ptePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptePanelMouseExited
        // TODO add your handling code here:
        ptePanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_ptePanelMouseExited

    private void ptePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptePanelMousePressed
        // TODO add your handling code here:
        ptePanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_ptePanelMousePressed

    private void ptePanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptePanelMouseReleased
        // TODO add your handling code here:
        ptePanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_ptePanelMouseReleased

    private void tsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tsPanelMouseEntered
        // TODO add your handling code here:
        tsPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_tsPanelMouseEntered

    private void tsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tsPanelMouseExited
        // TODO add your handling code here:
        tsPanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_tsPanelMouseExited

    private void tsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tsPanelMousePressed
        // TODO add your handling code here:
        tsPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_tsPanelMousePressed

    private void tsPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tsPanelMouseReleased
        // TODO add your handling code here:
        tsPanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_tsPanelMouseReleased

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered

    }//GEN-LAST:event_jLabel14MouseEntered

    private void ptbPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptbPanelMouseEntered
        // TODO add your handling code here:
        ptbPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_ptbPanelMouseEntered

    private void ptbPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptbPanelMouseExited
        // TODO add your handling code here:
        ptbPanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_ptbPanelMouseExited

    private void ptbPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptbPanelMousePressed
        // TODO add your handling code here:
        ptbPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_ptbPanelMousePressed

    private void ptbPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptbPanelMouseReleased
        // TODO add your handling code here:
        ptbPanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_ptbPanelMouseReleased

    private void tabogPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabogPanelMouseEntered
        // TODO add your handling code here:
        tabogPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_tabogPanelMouseEntered

    private void tabogPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabogPanelMouseExited
        // TODO add your handling code here:
        tabogPanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_tabogPanelMouseExited

    private void tabogPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabogPanelMousePressed
        // TODO add your handling code here:
        tabogPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_tabogPanelMousePressed

    private void tabogPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabogPanelMouseReleased
        // TODO add your handling code here:
        tabogPanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_tabogPanelMouseReleased

    private void tabusPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabusPanelMouseEntered
        // TODO add your handling code here:
        tabusPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_tabusPanelMouseEntered

    private void tabusPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabusPanelMouseExited
        // TODO add your handling code here:
        tabusPanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_tabusPanelMouseExited

    private void tabusPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabusPanelMousePressed
        // TODO add your handling code here:
        tabusPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_tabusPanelMousePressed

    private void tabusPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabusPanelMouseReleased
        // TODO add your handling code here:
        tabusPanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_tabusPanelMouseReleased

    private void trPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trPanelMouseEntered
        // TODO add your handling code here:
        trPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_trPanelMouseEntered

    private void trPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trPanelMouseExited
        // TODO add your handling code here:
        trPanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_trPanelMouseExited

    private void trPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trPanelMousePressed
        // TODO add your handling code here:
        trPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_trPanelMousePressed

    private void trPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trPanelMouseReleased
        // TODO add your handling code here:
        trPanel.setBackground(new Color (189, 195, 199));
    }//GEN-LAST:event_trPanelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel ptbPanel;
    private javax.swing.JPanel ptePanel;
    private javax.swing.JPanel ptiPanel;
    private javax.swing.JPanel ptmPanel;
    private javax.swing.JPanel siPanel;
    private javax.swing.JPanel tabogPanel;
    private javax.swing.JPanel tabusPanel;
    private javax.swing.JPanel tePanel;
    private javax.swing.JPanel tiPanel;
    private javax.swing.JPanel tmPanel;
    private javax.swing.JPanel trPanel;
    private javax.swing.JPanel tsPanel;
    // End of variables declaration//GEN-END:variables
}
