/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.appperpustakaan;

import java.awt.Color;

/**
 *
 * @author nasan
 */
public class RakBuku extends javax.swing.JFrame {

    /**
     * Creates new form RakBuku
     */
    public RakBuku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ftPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fvPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        fkPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        fbsPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        fipPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        febPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        fisipolPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        fikkPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        fmipaPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RAK BUKU");

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jPanel3.setBackground(new java.awt.Color(52, 73, 94));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.gray, java.awt.Color.darkGray));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nasan\\OneDrive\\Pictures\\logo_unesa1.png")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Urdu Typesetting", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("RAK BUKU");

        ftPanel.setBackground(new java.awt.Color(189, 195, 199));
        ftPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ftPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ftPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ftPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ftPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ftPanelMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Fakultas Teknik");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout ftPanelLayout = new javax.swing.GroupLayout(ftPanel);
        ftPanel.setLayout(ftPanelLayout);
        ftPanelLayout.setHorizontalGroup(
            ftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ftPanelLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ftPanelLayout.setVerticalGroup(
            ftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ftPanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        fvPanel.setBackground(new java.awt.Color(189, 195, 199));
        fvPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fvPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fvPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fvPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fvPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fvPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fvPanelMouseReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Fakultas Vokasi");

        javax.swing.GroupLayout fvPanelLayout = new javax.swing.GroupLayout(fvPanel);
        fvPanel.setLayout(fvPanelLayout);
        fvPanelLayout.setHorizontalGroup(
            fvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fvPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(183, 183, 183))
        );
        fvPanelLayout.setVerticalGroup(
            fvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fvPanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        fkPanel.setBackground(new java.awt.Color(189, 195, 199));
        fkPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fkPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fkPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fkPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fkPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fkPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fkPanelMouseReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Fakultas Kedokteran");

        javax.swing.GroupLayout fkPanelLayout = new javax.swing.GroupLayout(fkPanel);
        fkPanel.setLayout(fkPanelLayout);
        fkPanelLayout.setHorizontalGroup(
            fkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fkPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(168, 168, 168))
        );
        fkPanelLayout.setVerticalGroup(
            fkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fkPanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        fbsPanel.setBackground(new java.awt.Color(189, 195, 199));
        fbsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fbsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fbsPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fbsPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fbsPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fbsPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fbsPanelMouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Fakultas Bahasa dan Seni");

        javax.swing.GroupLayout fbsPanelLayout = new javax.swing.GroupLayout(fbsPanel);
        fbsPanel.setLayout(fbsPanelLayout);
        fbsPanelLayout.setHorizontalGroup(
            fbsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fbsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(154, 154, 154))
        );
        fbsPanelLayout.setVerticalGroup(
            fbsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fbsPanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        fipPanel.setBackground(new java.awt.Color(189, 195, 199));
        fipPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fipPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fipPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fipPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fipPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fipPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fipPanelMouseReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Fakultas Ilmu Pendidikan");

        javax.swing.GroupLayout fipPanelLayout = new javax.swing.GroupLayout(fipPanel);
        fipPanel.setLayout(fipPanelLayout);
        fipPanelLayout.setHorizontalGroup(
            fipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fipPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(151, 151, 151))
        );
        fipPanelLayout.setVerticalGroup(
            fipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fipPanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        febPanel.setBackground(new java.awt.Color(189, 195, 199));
        febPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        febPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                febPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                febPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                febPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                febPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                febPanelMouseReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Fakultas Ekonomi dan Bisnis");

        javax.swing.GroupLayout febPanelLayout = new javax.swing.GroupLayout(febPanel);
        febPanel.setLayout(febPanelLayout);
        febPanelLayout.setHorizontalGroup(
            febPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, febPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(137, 137, 137))
        );
        febPanelLayout.setVerticalGroup(
            febPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, febPanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        fisipolPanel.setBackground(new java.awt.Color(189, 195, 199));
        fisipolPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fisipolPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fisipolPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fisipolPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fisipolPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fisipolPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fisipolPanelMouseReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Fakultas Ilmu Sosial dan Hukum");

        javax.swing.GroupLayout fisipolPanelLayout = new javax.swing.GroupLayout(fisipolPanel);
        fisipolPanel.setLayout(fisipolPanelLayout);
        fisipolPanelLayout.setHorizontalGroup(
            fisipolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fisipolPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(127, 127, 127))
        );
        fisipolPanelLayout.setVerticalGroup(
            fisipolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fisipolPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        fikkPanel.setBackground(new java.awt.Color(189, 195, 199));
        fikkPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fikkPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fikkPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fikkPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fikkPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fikkPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fikkPanelMouseReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Fakultas Ilmu Keolahragaan dan Kesehatan");

        javax.swing.GroupLayout fikkPanelLayout = new javax.swing.GroupLayout(fikkPanel);
        fikkPanel.setLayout(fikkPanelLayout);
        fikkPanelLayout.setHorizontalGroup(
            fikkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fikkPanelLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel12)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        fikkPanelLayout.setVerticalGroup(
            fikkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fikkPanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        fmipaPanel.setBackground(new java.awt.Color(189, 195, 199));
        fmipaPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fmipaPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fmipaPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fmipaPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fmipaPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fmipaPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fmipaPanelMouseReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Fakultas Matematika dan Ilmu Pengetahuan Alam");

        javax.swing.GroupLayout fmipaPanelLayout = new javax.swing.GroupLayout(fmipaPanel);
        fmipaPanel.setLayout(fmipaPanelLayout);
        fmipaPanelLayout.setHorizontalGroup(
            fmipaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fmipaPanelLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fmipaPanelLayout.setVerticalGroup(
            fmipaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fmipaPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fbsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fvPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fipPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(febPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fisipolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fikkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fmipaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(6, 203, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(190, 190, 190))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(ftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fvPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fbsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fipPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(febPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fisipolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fikkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fmipaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ftPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftPanelMouseEntered
        // TODO add your handling code here:
        ftPanel.setBackground(new Color(189,195,199));
    }//GEN-LAST:event_ftPanelMouseEntered

    private void ftPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftPanelMouseExited
        // TODO add your handling code here:
        ftPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_ftPanelMouseExited

    private void ftPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftPanelMousePressed
        // TODO add your handling code here:
        ftPanel.setBackground(new Color(189,195,199));
    }//GEN-LAST:event_ftPanelMousePressed

    private void ftPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftPanelMouseReleased
        // TODO add your handling code here:
        ftPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_ftPanelMouseReleased

    private void fvPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fvPanelMouseEntered
        // TODO add your handling code here:
        fvPanel.setBackground(new Color(189,195,199));
    }//GEN-LAST:event_fvPanelMouseEntered

    private void fvPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fvPanelMouseExited
        // TODO add your handling code here:
        fvPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_fvPanelMouseExited

    private void fvPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fvPanelMousePressed
        // TODO add your handling code here:
        fvPanel.setBackground(new Color(189,195,199));
    }//GEN-LAST:event_fvPanelMousePressed

    private void fvPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fvPanelMouseReleased
        // TODO add your handling code here:
        fvPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_fvPanelMouseReleased

    private void fkPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fkPanelMouseEntered
        // TODO add your handling code here:
        fkPanel.setBackground(new Color(189,195,199));
    }//GEN-LAST:event_fkPanelMouseEntered

    private void fkPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fkPanelMouseExited
        // TODO add your handling code here: 
        fkPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_fkPanelMouseExited

    private void fkPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fkPanelMousePressed
        // TODO add your handling code here:
        fkPanel.setBackground(new Color(189,195,199));
    }//GEN-LAST:event_fkPanelMousePressed

    private void fkPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fkPanelMouseReleased
        // TODO add your handling code here:
        fkPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_fkPanelMouseReleased

    private void fbsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbsPanelMouseEntered
        // TODO add your handling code here:
        fbsPanel.setBackground(new Color(189,195,199));
    }//GEN-LAST:event_fbsPanelMouseEntered

    private void fbsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbsPanelMouseExited
        // TODO add your handling code here:
        fbsPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_fbsPanelMouseExited

    private void fbsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbsPanelMousePressed
        // TODO add your handling code here:
        fbsPanel.setBackground(new Color(189,195,199));
    }//GEN-LAST:event_fbsPanelMousePressed

    private void fbsPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbsPanelMouseReleased
        // TODO add your handling code here:
        fbsPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_fbsPanelMouseReleased

    private void fipPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fipPanelMouseEntered
        // TODO add your handling code here:
        fipPanel.setBackground(new Color(189,195,199));
    }//GEN-LAST:event_fipPanelMouseEntered

    private void fipPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fipPanelMouseExited
        // TODO add your handling code here:
        fipPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_fipPanelMouseExited

    private void fipPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fipPanelMousePressed
        // TODO add your handling code here:
        fipPanel.setBackground(new Color(189,195,199));
    }//GEN-LAST:event_fipPanelMousePressed

    private void fipPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fipPanelMouseReleased
        // TODO add your handling code here:
        fipPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_fipPanelMouseReleased

    private void febPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_febPanelMouseEntered
        // TODO add your handling code here:
        febPanel.setBackground(new Color(189,195,199));
    }//GEN-LAST:event_febPanelMouseEntered

    private void febPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_febPanelMouseExited
        // TODO add your handling code here:
        febPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_febPanelMouseExited

    private void febPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_febPanelMousePressed
        // TODO add your handling code here:
        febPanel.setBackground(new Color(189,195,199));
    }//GEN-LAST:event_febPanelMousePressed

    private void febPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_febPanelMouseReleased
        // TODO add your handling code here:
        febPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_febPanelMouseReleased

    private void fisipolPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fisipolPanelMouseEntered
        // TODO add your handling code here:
        fisipolPanel.setBackground(new Color(189,195,199));
    }//GEN-LAST:event_fisipolPanelMouseEntered

    private void fisipolPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fisipolPanelMouseExited
        // TODO add your handling code here:
        fisipolPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_fisipolPanelMouseExited

    private void fisipolPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fisipolPanelMousePressed
        // TODO add your handling code here:
        fisipolPanel.setBackground(new Color(189,195,199));
    }//GEN-LAST:event_fisipolPanelMousePressed

    private void fisipolPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fisipolPanelMouseReleased
        // TODO add your handling code here:
        fisipolPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_fisipolPanelMouseReleased

    private void fikkPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fikkPanelMouseEntered
        // TODO add your handling code here:
        fikkPanel.setBackground(new Color(189,195,199));
    }//GEN-LAST:event_fikkPanelMouseEntered

    private void fikkPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fikkPanelMouseExited
        // TODO add your handling code here:
        fikkPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_fikkPanelMouseExited

    private void fikkPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fikkPanelMousePressed
        // TODO add your handling code here:
        fikkPanel.setBackground(new Color(189,195,199));
    }//GEN-LAST:event_fikkPanelMousePressed

    private void fikkPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fikkPanelMouseReleased
        // TODO add your handling code here:
        fikkPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_fikkPanelMouseReleased

    private void fmipaPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fmipaPanelMouseEntered
        // TODO add your handling code here:
        fmipaPanel.setBackground(new Color(189,195,199));
    }//GEN-LAST:event_fmipaPanelMouseEntered

    private void fmipaPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fmipaPanelMouseExited
        // TODO add your handling code here:
        fmipaPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_fmipaPanelMouseExited

    private void fmipaPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fmipaPanelMousePressed
        // TODO add your handling code here:
        fmipaPanel.setBackground(new Color(189,195,199));
    }//GEN-LAST:event_fmipaPanelMousePressed

    private void fmipaPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fmipaPanelMouseReleased
        // TODO add your handling code here:
        fmipaPanel.setBackground(new Color(155, 89, 182));
    }//GEN-LAST:event_fmipaPanelMouseReleased
   
    private void ftPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftPanelMouseClicked
        // TODO add your handling code here:
        FT n = new FT();
        n.setVisible(true);
    }//GEN-LAST:event_ftPanelMouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered

    }//GEN-LAST:event_jLabel4MouseEntered

    private void fvPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fvPanelMouseClicked
        // TODO add your handling code here:
        FV n = new FV();
        n.setVisible(true);
    }//GEN-LAST:event_fvPanelMouseClicked

    private void fkPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fkPanelMouseClicked
        // TODO add your handling code here:
        FK n = new FK();
        n.setVisible(true);
    }//GEN-LAST:event_fkPanelMouseClicked

    private void fbsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbsPanelMouseClicked
        // TODO add your handling code here:
        FBS n = new FBS();
        n.setVisible(true);
    }//GEN-LAST:event_fbsPanelMouseClicked

    private void fipPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fipPanelMouseClicked
        // TODO add your handling code here:
        FIP n = new FIP();
        n.setVisible(true);
    }//GEN-LAST:event_fipPanelMouseClicked

    private void febPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_febPanelMouseClicked
        // TODO add your handling code here:
        FEB n = new FEB();
        n.setVisible(true);
    }//GEN-LAST:event_febPanelMouseClicked

    private void fisipolPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fisipolPanelMouseClicked
        // TODO add your handling code here:
        FISH n = new FISH();
        n.setVisible(true);
    }//GEN-LAST:event_fisipolPanelMouseClicked

    private void fikkPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fikkPanelMouseClicked
        // TODO add your handling code here:
        FIKK n = new FIKK();
        n.setVisible(true);
    }//GEN-LAST:event_fikkPanelMouseClicked

    private void fmipaPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fmipaPanelMouseClicked
        // TODO add your handling code here:
        FMIPA n = new FMIPA();
        n.setVisible(true);
    }//GEN-LAST:event_fmipaPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RakBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RakBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RakBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RakBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RakBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fbsPanel;
    private javax.swing.JPanel febPanel;
    private javax.swing.JPanel fikkPanel;
    private javax.swing.JPanel fipPanel;
    private javax.swing.JPanel fisipolPanel;
    private javax.swing.JPanel fkPanel;
    private javax.swing.JPanel fmipaPanel;
    private javax.swing.JPanel ftPanel;
    private javax.swing.JPanel fvPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
